name: built_rx_bloc
description: Bloc pattern implementation using Built Value for state and RxDart.
version: 0.0.3
repository: https://github.com/AmiK2001/built_rx_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.3
  built_value: ^8.1.3

dev_dependencies:
  flutter_lints: ^1.0.0